#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# pretty diff(need to install diff-so-fancy)
# brew install diff-so-fancy ORRRR npm i -g diff-so-fancy
function dff(){
    diff -u $@ | diff-so-fancy | less --tabs=4 -RFX
}

# for history-substring-search module, this configuration may no longer be needed in the future
export HISTORY_SUBSTRING_SEARCH_PREFIXED=true
export HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=true

# Common Env
export EDITOR='vim'
export VISUAL='vim'

if [[ "$OSTYPE" =~ ^darwin ]]; then
    export DEV_TOOLS="${HOME}/devtools"

    # GNU tools
    # brew install coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt grep
    #
    #export PATH="/usr/local/opt/coreutils/libexec/gnubin:${PATH}"
    export PATH="/usr/local/opt/findutils/libexec/gnubin:${PATH}"
    export PATH="/usr/local/opt/gnu-tar/libexec/gnubin:${PATH}"
    export PATH="/usr/local/opt/gnu-sed/libexec/gnubin:${PATH}"
    export PATH="/usr/local/opt/gnu-indent/libexec/gnubin:${PATH}"
    export PATH="/usr/local/opt/gnu-getopt/bin:${PATH}"
    export PATH="/usr/local/opt/grep/libexec/gnubin:${PATH}"

    # curl
    export PATH="/usr/local/opt/curl/bin:${PATH}"
    
    # For compilers to find curl
    export LDFLAGS="-L/usr/local/opt/curl/lib"
    export CPPFLAGS="-I/usr/local/opt/curl/include"

    # For pkg-config to find curl
    export PKG_CONFIG_PATH="/usr/local/opt/curl/lib/pkgconfig"

    # iTerm2
    test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

    # User Secret 
    test -e "${HOME}/.user.secret" && source "${HOME}/.user.secret"
else
    export DEV_TOOLS="/opt/devtools"
fi

export GOPATH="${HOME}/gopath"
export GOROOT="${DEV_TOOLS}/go"
export PATH="${GOROOT}/bin:${GOPATH}/bin:${PATH}"

export JAVA_HOME="${DEV_TOOLS}/openjdk11"
export PATH="${JAVA_HOME}/bin:${PATH}"

export M2_HOME="${DEV_TOOLS}/maven"
export PATH="${M2_HOME}/bin:${PATH}"

export NODE_HOME="${DEV_TOOLS}/nodejs"
export PATH="${NODE_HOME}/bin:${PATH}"

export SONAR_SCANNER="${DEV_TOOLS}/sonar-scanner"
export PATH="${SONAR_SCANNER}/bin:${PATH}"

alias tmux='tmux attach-session -d'
alias dc='docker-compose'

