#
# Executes commands at the start of an interactive session.
#
# Authors:
#   mritd <mritd@linux.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
    source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# pretty diff(need to install diff-so-fancy)
# brew install diff-so-fancy ORRRR npm i -g diff-so-fancy
function dff(){
    diff -u $@ | diff-so-fancy | less --tabs=4 -RFX
}

# fix systemd
# https://github.com/ohmyzsh/ohmyzsh/issues/8751
function _systemctl_unit_state() {
  typeset -gA _sys_unit_state
  _sys_unit_state=( $(__systemctl list-unit-files "$PREFIX*" | awk '{print $1, $2}') )
}

# for history-substring-search module, this configuration may no longer be needed in the future
export HISTORY_SUBSTRING_SEARCH_PREFIXED=true
export HISTORY_SUBSTRING_SEARCH_ENSURE_UNIQUE=true

# Common Env
export EDITOR='vim'
export VISUAL='vim'

# Use default grep colors
export GREP_COLOR='01;31'
export GREP_COLORS='mt=01;31'

# For macOS
if [[ "$OSTYPE" =~ ^darwin ]]; then
    # brew
    eval "$(/opt/homebrew/bin/brew shellenv)"

    # env
    export DEV_TOOLS="${HOME}/devtools"

    # GNU tools
    # brew install coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt grep
    #
    #export PATH="/opt/homebrew/opt/coreutils/libexec/gnubin:${PATH}"
    export PATH="${HOMEBREW_PREFIX}/opt/findutils/libexec/gnubin:${PATH}"
    export PATH="${HOMEBREW_PREFIX}/opt/gnu-tar/libexec/gnubin:${PATH}"
    export PATH="${HOMEBREW_PREFIX}/opt/gnu-sed/libexec/gnubin:${PATH}"
    export PATH="${HOMEBREW_PREFIX}/opt/gnu-indent/libexec/gnubin:${PATH}"
    export PATH="${HOMEBREW_PREFIX}/opt/gnu-getopt/bin:${PATH}"
    export PATH="${HOMEBREW_PREFIX}/opt/grep/libexec/gnubin:${PATH}"

    # OpenSSL
    # brew install openssl
    export PATH="${HOMEBREW_PREFIX}/opt/openssl@3/bin:${PATH}"
    #export LDFLAGS="-L${HOMEBREW_PREFIX}/opt/openssl@3/lib"
    #export CPPFLAGS="-I${HOMEBREW_PREFIX}/opt/openssl@3/include"
    #export PKG_CONFIG_PATH="${HOMEBREW_PREFIX}/opt/openssl@3/lib/pkgconfig"

    # curl
    # brew install curl
    export PATH="${HOMEBREW_PREFIX}/opt/curl/bin:${PATH}"
    #export LDFLAGS="-L${HOMEBREW_PREFIX}/opt/curl/lib"
    #export CPPFLAGS="-I${HOMEBREW_PREFIX}/opt/curl/include"
    #export PKG_CONFIG_PATH="${HOMEBREW_PREFIX}/opt/curl/lib/pkgconfig"
    
    # mysql
    export PATH="${HOMEBREW_PREFIX}/opt/mysql-client/bin:${PATH}"

    # alias
    alias tmux='tmux attach-session -d'
fi

# For Linux
if [[ "$OSTYPE" =~ ^linux ]]; then
    # env
    export DEV_TOOLS="/opt/devtools"
fi

# User Secret 
# Define the secret configuration in this file, prezto automatically loads it
test -e "${HOME}/.user.secret" && source "${HOME}/.user.secret"

# Golang
export GOPATH="${HOME}/gopath"
export GOROOT="${DEV_TOOLS}/go"
export PATH="${GOROOT}/bin:${GOPATH}/bin:${PATH}"

# TinyGo
export TINYGO_HOME="${DEV_TOOLS}/tinygo"
export PATH="${TINYGO_HOME}/bin:${PATH}"

# Rust
export PATH="${HOME}/.cargo/bin:${PATH}"

# Java
export JAVA_HOME="${DEV_TOOLS}/openjdk11"
export PATH="${JAVA_HOME}/bin:${PATH}"

# Maven
export M2_HOME="${DEV_TOOLS}/maven"
export PATH="${M2_HOME}/bin:${PATH}"

# Nodejs
export NODE_HOME="${DEV_TOOLS}/nodejs"
export PATH="${NODE_HOME}/bin:${PATH}"

# Sonar
export SONAR_SCANNER="${DEV_TOOLS}/sonar-scanner"
export PATH="${SONAR_SCANNER}/bin:${PATH}"

# Docker build default platform
export DOCKER_DEFAULT_PLATFORM="linux/amd64"

# Common Aliases
#
# Overwrite Aliases
# see also: https://github.com/sorin-ionescu/prezto/blob/master/modules/utility/init.zsh
alias l='ls -alh'
alias lm='ls -alh | "$PAGER"'

# Custom Aliases
alias kuebctl='kubectl'
alias dc='docker compose'
